### ISSUE TITLE
Command parameters order mismatch

### ISSUE THREAD

**Issue by GalTzemach** [kawansoft/AceQL.Client#11]
When AceQL convert the sql to http, the number of the parameters determined by the order that them wrote.
With no consideration the names of the parameters.

Which means that there is no any meaning to the @name of parameters in the sql query?!

Illustrating the problem:
SELECT * FROM table_name WEHRE column1 = @param1 and column2 = @param2;
command.Parameters.AddWithValue("@param2", value2);
command.Parameters.AddWithValue("@param1", value1);

In this situation, everything mix, the value2 go to param1and so on.

**Comment by ndepomereu** [comment]
Hi Gal,
THis is a bug, I will fix it today.

**Comment by GalTzemach** [comment]
I am waiting..
it's a very important and urgent to me.

Thanks a lot!

**Comment by ndepomereu** [comment]
Hi Gal,
New version 5.4.0 is on line and fixes the order problem.

**Comment by GalTzemach** [comment]
Thanks.
