### ISSUE TITLE
Api key/ Authorization Headers in Aceql

### ISSUE THREAD

**Issue by santhosh250595** [kawansoft/AceQL.Client#12]
Hello Nicolas,

Is there any option to add Api keys and Authorization headers to HttpClient in AceQL.

**Comment by ndepomereu** [comment]
Hi Santosh,
Could you please more specifics?
I understand you want to add your own HTTP Headers, which would be possible in a feature release.
What do you mean by API keys?

**Comment by santhosh250595** [comment]
Hello Nicolas,

I want to add something like this below to httpclient.
HttpRequestMessage request;
request.Headers.Add("api_key", "1234");

**Comment by ndepomereu** [comment]
Thanks  Santosh, it's clear now.
For implementation: it would be done at each HTTP call, is this OK for you?

**Comment by santhosh250595** [comment]
Hello Nicolas,
Should be fine.
Thanks.
Have a happy weekend.

**Comment by ndepomereu** [comment]
Hi Santosh,
- The new AceQLConnection.AddRequestHeader(string name, string value) allows
  to set request headers for the session. 
  AceQLConnection.ResetRequestHeaders() allows to reset (added headers are
  suppressed in subsequent requests).

**Comment by santhosh250595** [comment]
Hello Nicolas,
FYI, Currently AddRequestHeader is non static method.
I'm using aceqlconnection object to access it.
Is this the way intended or got missed to add static.

**Comment by ndepomereu** [comment]
Hi Sanstosh,
This is is done on purpose . As we could imagine in a C# program 2 simultaneous sessions that would require different headers.
