### ISSUE TITLE
Stored Procedure parameters mismatch

### ISSUE THREAD

**Issue by GalTzemach** [kawansoft/AceQL.Client#13]
I get the following Exception:
"Error converting data type nvarchar to int."

**Comment by ndepomereu** [comment]
Please send the C# & Aceql code that induces the error.

**Comment by ndepomereu** [comment]
Hi Gal,
Decimal is not supported for now in C#.
I suggest to convert to Double before passing parameter:
https://stackoverflow.com/questions/5571485/converting-decimal-to-double-in-c

**Comment by GalTzemach** [comment]
it might be that ver 4.2.2 works and 5.4.0 not?

**Comment by GalTzemach** [comment]
Or maybe in Stored Procedure still have mismatch in the params orders?

**Comment by GalTzemach** [comment]
I found that, there is no any connection between the parameter names and values. Only the order of add of the parameters determines their order.

**Comment by ndepomereu** [comment]
Thanks, I will check that and fix it asap.

**Comment by GalTzemach** [comment]
Do you have some estimation please?Do you have some estimation please?
It's look like similar issue to text sql right?

**Comment by ndepomereu** [comment]
I don't know, I will work on it later today.

**Comment by GalTzemach** [comment]
Any news please?

**Comment by ndepomereu** [comment]
HI Gal,
I have re-tested stored procedures with last server version (6.0).
Everything works fine, even if I change the order of parameters.
The parameters treatments is the same for a regular Statement.

Please send code sample, awaited result, and the defect happening so that I can find the problem.

**Comment by GalTzemach** [comment]
There is some different between versions 6.0 and 5.1-PATCH-2.0 in this subject?

**Comment by ndepomereu** [comment]
I don't think so, but it's better to upgrade if you can...

**Comment by GalTzemach** [comment]
Thanks, i will test it with ver 6.0 and update..

**Comment by GalTzemach** [comment]
What is the right way for the above upgrade?

**Comment by GalTzemach** [comment]
Can i replace the "aceql-http-VERSION.jar" file only?
If yes, how cav i get this file only?

**Comment by GalTzemach** [comment]
So, after carefully checks, i found that there are two issues:

1. There is no match between CommandText params and params that added after that by: `command.Parameters.AddWithValue(...)`.
Already fixed in Client SDK - Version 5.4.

2. There is no match between the name of the params in the CommandText and the name of the params in the Stored Procedure.
Even if i write diff names it's works, but whitch means that the first param of the CommandText go to the first param of the SP just bacause the order and there is no meaning to the names of the params (unlike sql of course).

It's clear now or do you need code exmples?

**Comment by ndepomereu** [comment]
My tests show no parameters mismatch with stored procedures, so I can't reproduce....
Maybe there is something I don't get.
Please send code, it will help a lot.
Thanks

**Comment by GalTzemach** [comment]
The followong code:
```
        public async Task SPAceQL()
        {
            string sql = "{call [dbo].[TestSP](@Param1, @Param2, @Param3)}";
            //string sql = "{call [dbo].[TestSP](@Param3, @Param2, @Param1)}";

            AceQLCommand command = new AceQLCommand(sql, AceQLConnection);
            try
            {
                command.CommandType = CommandType.StoredProcedure;

                command.Parameters.AddWithValue("@Param1", 11);
                command.Parameters.AddWithValue("@Param2", "two");
                command.Parameters.AddWithValue("@Param3", 33);

                await command.ExecuteNonQueryAsync();

                Console.WriteLine("SP Done");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }
```
Not Doing the same for both sql order (the values remains same):
```
            string sql = "{call [dbo].[TestSP](@Param1, @Param2, @Param3)}";
            string sql = "{call [dbo].[TestSP](@Param3, @Param2, @Param1)}";
```
And even if i replace the names of params in sql to random names like:
```
            string sql = "{call [dbo].[TestSP](@ParamA1, @ParamBB2, @ParamCCC3)}";
```
It's works.

While the names of the params in the SP is:
```
ALTER PROCEDURE [dbo].[TestSP] 
	-- Add the parameters for the stored procedure here
	--<@Param1, sysname, @p1> <Datatype_For_Param1, , int> = <Default_Value_For_Param1, , 0>, 
	--<@Param2, sysname, @p2> <Datatype_For_Param2, , int> = <Default_Value_For_Param2, , 0>
	@Param1 int,
	@Param2 varchar(50),
	@Param3 int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	--SELECT <@Param1, sysname, @p1>, <@Param2, sysname, @p2>
	INSERT INTO [dbo].[AceQLTst2] ([test1], [test2], [test3]) VALUES (@Param1, @Param2, @Param3) 
END
```
Which means, there is no match between the names of params in the sql and the names of params in the SP.
Simply the first in the sql go to the first in the SP with no any meaning to the names.

**Comment by ndepomereu** [comment]
Hi Gal,
This is normal.
The server uses a JDBC Driver that supports only the parameter order as called from the client side, becauseJava has no parameter name substitution, but uses natural order with ? for each parm.

So when calling somethign like: 
`string sql = "{call ProcedureName(@parm1, @parm2, @parm3)}";`
It will replaced by 
"{call ProcedureName(?, ?, ?) }" on server side because we are in Java/JDBC and not any more in C#.

This is a feature and not a bug.

**Comment by GalTzemach** [comment]
OK.. Thanks.
So if i have case of SP with multiple params and in the C# method/code i need to pass variable number of params depends on some logic, how can i do it? 
I mean if i need to pass params to the 1,3,6 (index/order) and not for 2,4,5 for example.

**Comment by ndepomereu** [comment]
The order of the parameters in the `string sql = "{call [dbo].[TestSP](@Param1, @Param2, @Param3)}";`
must be the order of declaration in the SP itself, aka in this case, @Param1,  @Param2, @Param3.

**Comment by GalTzemach** [comment]
Thanks!
