### ISSUE TITLE
Not an issue. Info about CloseAsync and LogoutAsync

### ISSUE THREAD

**Issue by santhosh250595** [kawansoft/AceQL.Client#14]
Hello Nicolas,

Hope you are doing good.

Can you elaborate the CloseAsync and LogoutAsync methods and How connections gets closed in both

Thanks in advance

**Comment by ndepomereu** [comment]
Hi Santosh,

- `CloseAsync ` will close only the current client session, and release on server side only one JDBC `Connection`.

- `LogoutAsync ` will close all current client sessions, and release all server sides JDBC `Connection`. This is useful if you have opened more than one session from the C# client side.

**Comment by santhosh250595** [comment]
Thanks for the info Nicolas
