### ISSUE TITLE
Read multiple result set

### ISSUE THREAD

**Issue by swapndeh** [kawansoft/AceQL.Client#18]
I have a stored procedure which is returning multiple result sets. How can i read all result sets using aceql data reader in c#?

Using SQL i can read all result sets using datareader.NextResult, do we have any way to read like this in Aceql data reader?

**Comment by ndepomereu** [comment]
Hi,
This feature is not yet implemented in AceQL.
Regards,

**Comment by swapndeh** [comment]
Thanks for the update.
