### ISSUE TITLE
Add of parameter with empty value like "" throws exception.

### ISSUE THREAD

**Issue by GalTzemach** [kawansoft/AceQL.Client#6]
I'm trying to convert my code to work with AceQL instead of direct connection to the DB. 

I found some issue regard to empty parameter. When i trying to add parameter with empty value like "", i get the following exception: "No parameter value for IN parameter index X" where x is the index of the relevant parameter.

Please let me know how should i add parameter with empty value?

**Comment by ndepomereu** [comment]
Hi  Gal,
You can't for now, this a defect of AceQL server side. 
We will fix that asap.
(Meanwhile, you can set to `null `or `" "` but not empty string `""`).

**Comment by GalTzemach** [comment]
Hi,

Thanks a lot!
There is some estimation for this fix?

Regards,
Gal.

בתאריך יום ב׳, 31 באוג׳ 2020, 00:09, מאת Nicolas de Pomereu ‏<
notifications@github.com>:

**Comment by ndepomereu** [comment]
Hi Gaz,
New fully packaged version should be released at end of this week,
But I will make an intermediary patch that fixes this problem today. I will notice you when it's ready.

**Comment by ndepomereu** [comment]
Hi Gal,

The fix is ready.
Just replace in your installation the `aceql-http-5.1.jar`  jar located in `lib-server` dir by this new one: 
https://github.com/kawansoft/aceql-http/blob/5.1-PATCH-1.0/dist/aceql-http-5.1-PATCH-1.0.jar

**Comment by GalTzemach** [comment]
Thank you so much!👍

‫בתאריך יום ב׳, 31 באוג׳ 2020 ב-13:49 מאת ‪Nicolas de Pomereu‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by GalTzemach** [comment]
I found one more issue.
Column header returns as lowercase even if the original header/key it's a
uppercase.

‫בתאריך יום ב׳, 31 באוג׳ 2020 ב-14:32 מאת ‪Gal Tzemach‬‏ <‪
galtzemach@gmail.com‬‏>:‬

**Comment by ndepomereu** [comment]
Hi,
This Will be fixed in next server version.
An intermediary patch will be done asap.
