### ISSUE TITLE
Column header return as lowercase always (even if the original header/key is not).

### ISSUE THREAD

**Issue by GalTzemach** [kawansoft/AceQL.Client#7]

**Comment by ndepomereu** [comment]
Hi,
This Will be fixed in next server version.
An intermediary patch will be done asap.

**Comment by GalTzemach** [comment]
Thanks.
Maybe do you have estimasion for the patch? it's a very urgent for me.

**Comment by ndepomereu** [comment]
Hi Gal,
This is fixed in cumulative patch 2.0 (that thus includes aceql-http-5.1-PATCH-1.0.jar):
https://github.com/kawansoft/aceql-http/blob/5.1-PATCH-2.0/dist/aceql-http-5.1-PATCH-2.0.jar

**Comment by GalTzemach** [comment]
Thanks a lot. It's working well.
