### ISSUE TITLE
How to adds parameters to Stored Procedure? I get an exception.

### ISSUE THREAD

**Issue by GalTzemach** [kawansoft/AceQL.Client#9]
For me, it's not work like SqlCommand:
...
command.Parameters.AddWithValue("@paramName", <value>);
command.ExecuteNonQuery();
...

I get the following exception:
**"Can not add value for the invalid parameter name: @TestParam".**

**Comment by ndepomereu** [comment]
Hi Gal,

Please see the samples:
https://github.com/kawansoft/AceQL.Client/blob/master/AceQL.Client.Tests/Test/MySqlStoredProcedureTest.cs
https://github.com/kawansoft/AceQL.Client/blob/master/AceQL.Client.Tests/Test/SqlServerStoredProcedureTest.cs
